version: 0.1.0{build}-rc

# branches:
#  only:
#    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

install:
    - nuget restore

build:
  project: Haarlemmertrekvaart.sln
  # verbosity: minimal
  verbosity: detailed

after_test:

  - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[AutoHashing]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"Haarlemmertrekvaart.UnitTests\bin\debug\Haarlemmertrekvaart.UnitTests.dll /domain:single /noshadow" -output:"coverage.xml"
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover "coverage.xml"
  - ps: .\nuget\publish.ps1

artifacts:
  - path: Haarlemmertrekvaart\bin\Release\Haarlemmertrekvaart.dll
    name: Haarlemmertrekvaart.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure:
#  artifact: /.*\.nupkg/
