version: 0.1.0.{build}

branches:
#  only:
#    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: Haarlemmertrekvaart.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Haarlemmertrekvaart\bin\Release\Haarlemmertrekvaart.dll
    name: Haarlemmertrekvaart.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure:
#  artifact: /.*\.nupkg/
